version: '3.8'
# version: '3.7'

services:
  composer:
    image: composer
    command: composer install
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app

  php:
    image: php:7.4-fpm
    build: .conf/php/
    restart: always
    expose:
      - 9001
    volumes:
      - .:/app
      - .conf/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .conf/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - .conf/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /app

  phpunit:
    image: php:7.4-fpm
    volumes:
      - .:/app
    working_dir: /app

  fpm:
    image: php:7.4-fpm
    restart: always
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - .conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  Mysqldb:
    container_name: mydb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin456
    volumes:
      - "my-data:/var/lib/mysql"
    networks:
      - network_mynet

volumes:
  my-data:
# //////////////////////////////
#   Pgdb:
#     container_name: mydb
#     image: postgres:14.1-alpine
#     # restart: always
#     ports:
#       - '5432:5432'
#     environment:
#       - POSTGRES_ROOT_PASSWORD=root
#       - POSTGRES_DATABASE=ratedb
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
    
#     volumes: 
#       - db:/var/lib/postgresql/data

# volumes:
#   db:
#     driver: local
# ///////////////////////////////
  
networks:
  network_mynet: